### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SalmanRai**

### CODE REVIEW

**Comment by jmsv** [comment]
# 🤔 ?

**Comment by SecondeJK** [comment]
Oh! This is a really super poor attempt at hacking.

**Comment by SalmanRai** [comment]
lol, just for pr bro 😀

Pada tanggal Sel, 5 Okt 2021 16.23, James Seconde ***@***.***>
menulis:

**Comment by SecondeJK** [comment]
Just a PR to attempt an old wordpress hack in a python module. You are an absolute **pro** at this.

**Comment by alxwrd** [comment]
It's a PR for hacktoberfest.

**Comment by SecondeJK** [comment]
If it's for hacktoberfest, you get two shots to make sure you don't submit nonsense, otherwise you get booted off it and can't claim. The author presumably knows that.

**Comment by bahorn** [comment]
There are creds in this for a database hosted in DigitalOcean's IP space, and they seem unique.

**If you took this from a project @SalmanRai you need to rotate them NOW.**

**Pull request closed without merging**
