### PR TITLE
Remove Pipfile.lock

### PR DESCRIPTION
**Pull request by alxwrd**
hello 👋 !

I was having an issue where getting an environment set up on a Windows machine was causing issues with `colorful` because `colorama` wasn't being installed. It's only a dependency on Windows, [see here](https://github.com/timofurrer/colorful/blob/master/requirements.txt#L3).

```shell
git clone https://github.com/jmsv/ety-python.git
cd ety-python
pipenv install .
python
>>> import ety
  File "...\site-packages\colorful\__init__.py", line 28, in <module>
    from colorama import init
ModuleNotFoundError: No module named 'colorama'
```

I've regenerated `Pipfile.lock` on a windows machine so `colorama` gets included. This has also bumped some version numbers, but tests are still passing locally.

### CODE REVIEW

**Comment by jmsv** [comment]
Whoops! always missing the windowsy problems

Doesn't `Pipfile.lock` get regenerated when adding dependecies? I'm worried this change could get easily overwritten in the future - could `colorama` be added as a dependency in `Pipfile`?

**Comment by alxwrd** [comment]
🤔 Maybe the solution here is to [remove `Pipfile.lock` from source control](https://github.com/kennethreitz/maya/issues/138)?

It seems weird to have `colorama` as an ety dependency because it's a `colorful` dependency.

**Comment by jmsv** [comment]
Ahhh that's a good idea. I didn't know about this:

> Do not keep Pipfile.lock in version control if multiple versions of Python are being targeted.

Feel free to update this PR removing `Pipfile.lock` and adding to `.gitignore`

**Comment by jmsv** [comment]
thanks @alxwrd :+1:

**Pull request merged**
